[package]
name = "patricia-trie"
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Merkle-Patricia Trie generic over key hasher and node encoding"
license = "GPL-3.0"

[dependencies]
elastic-array = "0.10"
log = "0.3"
rand = "0.4"
ethcore-bytes = { version = "0.1.0", path = "../bytes" }
hashdb = { version = "0.2", path = "../hashdb" }
ethcore-logger = { version = "1.9.0", path = "../../logger" }
stream-encoder = { path = "../stream-encoder" }

[dev-dependencies]
triehash = { version = "0.1.0", path = "../triehash" }
memorydb = { version = "0.2", path = "../memorydb" }
ethereum-types = "0.3"
keccak-hash = { version = "0.1.0", path = "../hash" }
keccak-hasher = { path = "../keccak-hasher" }
rlp = { version = "0.2.1", path = "../rlp" }
trie-standardmap = { path = "../trie-standardmap" }
patricia-trie-ethereum = { path = "../patricia-trie-ethereum" }
env_logger = "*" # TODO: remove